#!/bin/bash

sudo chmod a+rw /dev/ttyACM0
cd $HOME
xterm -hold -e "roscore" &
xterm -hold -e "MOOSDB" &
cd $HOME/moos-ros-bridge/moosros
xterm -hold -e "rosrun moosros Bridge sailboat.xml bridge.moos" &
source $HOME/catkin_ws/devel/setup.bash
xterm -hold -e "rosrun rosserial_python serial_node.py /dev/ttyACM0" &
xterm -hold -e "rosrun sailboat listen" &
xterm -hold -e "rosrun sailboat motorcontrol" &

exit 0

